sass:
  style: compressed
  sass_dir: assets/css
  load_paths: [ _includes/**/*, _pages/**/* ]
collections:
  authors:
    output: true
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      JEKYLL_ENV": "production"
include: [ '_pages' ]
imgPrefix: "assets/img/"
plugins:
  - jekyll-gzip
  - jekyll-sitemap
