name: Production Build and Deploy
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
jobs:
  call-deployment-workflow:
    uses: ./.github/workflows/deploy-site.yml
    with:
      envName: production
      envUrl: implex.dev
      envRepoName: implex-code-repo/implex-site-prod
      GA_id: UA-163722668-1
      TM_id: GTM-5TK5WJ8
    secrets:
      envPAT: ${{ secrets.PAT }}
